### ISSUE TITLE
Inconsistent and/or incorrect output

### ISSUE THREAD

**Issue by dkjajhqu2h3j** [Leo4j/Invoke-SessionHunter#1]
Hi,

I see a lot of potential in this tool. However, at the moment I encounter several issues testing this in my lab. Note that the below commands are executed in the same session and one command after the other.

1) Executing `Invoke-SessionHunter` logged in as the low priv. user account `adlab1_domainuser1` correctly outputs two computers on which the DA `adlab1_domainadmin1` has a session. So far so good.
2) Executing `Invoke-SessionHunter -CheckAsAdmin -UserName "adlab1.local\adlab1_domainadmin1" -Password "Passw0rd!"`, using the DA account, only one computer is outputted and the only session that is shown is from the computer account of the workstation (`workstation1`) that this script is executed on... I was expecting to the see the same output as in step 1 with the difference that I would have privileged access. I also was not expecting to see any computer account sessions in general and certainly not one from the same computer (`workstation1`) the script is running on...
3) Executing `Invoke-SessionHunter -UserName "adlab1.local\adlab1_domainadmin1" -Password "Passw0rd!"` I get the same incorrect output as in step 2. Since `-CheckAsAdmin` no longer is used I was expecting a different output (other than the incorrect output of course).
4) Finally, exeuting the same command as in step 3 again I suddenly get no output at all... 

Rebooting the workstation on which the script is executed, I start to get output again. However, that should not be required and if I redo the above steps I get the same errors...

![pic1](https://github.com/user-attachments/assets/76c1f2eb-2e62-43b5-83e4-dd48409fda69)

**Comment by Leo4j** [comment]
Hi there, thanks for raising this, I'll try and explain the tool behavior.

Starting from point 2 and 3, the output is perfectly identical because if you provide a Username and Password the tool will automatically CheckAsAdmin. Given that you don't need admin privileges to read the remote registry, providing credentials should yield no different results. In cases where you do need admin privs then credentials can be provided.

When checking as admin, the results are obtained running the "klist sessions" command on the target, then parsed and printed on screen. Some of these results are filtered out. Specifically:

- any session related to the target machine (DC1 or SCCM)
- any session related to the username you provide (adlab1_domainadmin1)

The assumption is that if you already hold a username and password of a user that has admin access to a machine, you most probably won't benefit from jumping on it and exploit the same user session. On the other hand, any other user would be interesting for lateral movement purposes.

Would you be able to try again and confirm ? This time try using different credentials from the domainadmin1 user (of course another local admin user or another DA) OR same credentials but different user session on the targets.

Hope this makes sense

In regard to point 4, I'm not sure why you're facing this issue, but seems related to the remote registry being stuck more than something not working properly within the tool. I'm not facing this issue in my lab, maybe try a different target and see if you face the same issue ?

Thanks

**Comment by Leo4j** [comment]
Hi there,

I've updated the ReadMe to explain this behavior, and implemented a -ShowAll switch that will retrieve all sessions, including those for the current user and the username provided.

Hope this helps

Thanks

**Comment by dkjajhqu2h3j** [comment]
Great! I will try the new parameter.

I can no longer reproduce 4 so never mind that.

A couple of questions related to large environments with thousands of computers :
1) I'm guessing your script gets the computer names from LDAP, if so, is there some filtering in place? For example, are disabled computer accounts ignored? I am aware of for example the parameter "-servers".
2) Will your script output partial results from time to time or will it wait until the enumeration is complete? In my lab it waits but that is a tiny environment.

**Comment by Leo4j** [comment]
The tool gathers only enabled machine objects, then runs a port scan to check which ones are alive, then proceeds.

At the moment it will show results once the enumeration is complete. I've tested this tool in large environments, of course there's some waiting time but not too much I have to say. It's fairly fast

Let me know how your tests go, then I'll close the issue if you happy with the outcome.

Thanks

**Comment by dkjajhqu2h3j** [comment]
Good!

I tested the parameters `-ShowAll` and `-IncludeLocalHost` which seems to work. This does however require the parameter `-checkAsAdmin` as well in the case of the localhost check. Something to note for oneself.

**Comment by dkjajhqu2h3j** [comment]
I also tested the `-Hunt` parameter and that does not seem to work.

![pic4](https://github.com/user-attachments/assets/f45035bc-7598-44ac-984f-6499b3c7512d)

**Comment by Leo4j** [comment]
-Hunt parameter is now fixed.

for the -IncludeLocalHost switch it works without -CheckAsAdmin, just you need to make sure you also use -ShowAll as most probably you're the only one logged in your machine and it won't show yourself otherwise

![image](https://github.com/user-attachments/assets/e239f129-397f-41b7-aa9b-a13dc026ba20)

**Comment by dkjajhqu2h3j** [comment]
`-Hunt` now works. Good!

I just reproduced the potential issue with using `-IncludeLocalHost` without also using `-CheckAsAdmin`.

![pic5](https://github.com/user-attachments/assets/85d0066e-cfc4-4e50-a322-b47978a9bbc7)

**Comment by Leo4j** [comment]
I can't reproduce your issue. It looks to me that is an issue with workstation1 remote registry being stuck or disabled.

When you use CheckAsAdmin the remote registry is skipped, and results are retrieved by running the "klist sessions" command on the machine, which explains why you get results. Keep an eye on the "Method" column.

In the tool main page you read:

"It's important to note that the remote registry service needs to be running on the remote computer for the tool to work effectively. In my tests, if the service is stopped but its Startup type is configured to "Automatic" or "Manual", the service will start automatically on the target computer once queried (this is native behavior), and sessions information will be retrieved. If set to "Disabled" no session information can be retrieved from the target."

Make sure the remote registry on your machine is not set to Disabled

Below is a screenshot of the same command being run on my lab

![image](https://github.com/user-attachments/assets/274525c8-2cf1-4de9-99bd-b814cb41913d)

**Comment by dkjajhqu2h3j** [comment]
OK. Thanks!

Is there a way to run this script using a domain account from a non domain-joined computer?

**Comment by Leo4j** [comment]
I haven't tested the tool in this regard, you could try opening a new command prompt and do a runas with the /netonly flag, then run the tool from there.

Closing this issue now as resolved.

Thanks for your input, and happy session hunting
